// SPDX-License-Identifier: AGPL-3.0-or-later
#pragma once
#include <cstddef>
#include <cstdint>
#include <span>
#include <vector>

#include "rkvc/diag.hpp"
#include "rkvc/result.hpp"

namespace mlvc {

// rANS entropy codec, a line-by-line C++ port of the C implementation
// (itself a port of Microsoft msrtc_rans, MIT). Bitstream-compatible:
// golden vectors generated by the C encoder must decode here and vice
// versa. Algorithms: ryg_rans / msrtc_rans (c) Microsoft Corporation.
enum class RansVariant : uint32_t {
    Byte = 0,  // 32-bit state, byte units
    Rans64 = 1,  // 64-bit state, 32-bit units
};

struct RansEncSym {
    uint32_t x_max_hi = 0;
    uint32_t freq_rcp_shift = 0;
    uint32_t freq_rcp = 0;
    uint32_t freq_rcp_hi = 0;  // Rans64 only
    uint32_t freq_cmpl = 0;
    uint32_t bias = 0;
};

struct RansDist {
    int32_t value_offset = 0;
    int32_t bypass_sentinel = 0;
    size_t enc_sym_offset = 0;
    size_t dec_cdf_offset = 0;
};

class RansCoder {
public:
    static rkvc::Result<RansCoder> create(
        RansVariant variant, std::span<const int32_t> lengths,
        std::span<const int32_t> offsets, std::span<const int32_t> table,
        int symbol_bits, int bypass_bits, rkvc::Diag* diag = nullptr);

    RansCoder() = default;
    RansVariant variant() const noexcept { return variant_; }
    int symbol_bits() const noexcept { return symbol_bits_; }
    int bypass_bits() const noexcept { return bypass_bits_; }
    uint32_t bypass_max() const noexcept { return bypass_max_; }
    const std::vector<RansDist>& dists() const noexcept { return dists_; }
    const std::vector<RansEncSym>& enc_syms() const noexcept {
        return enc_syms_;
    }
    const std::vector<uint32_t>& cdf_table() const noexcept {
        return cdf_table_;
    }

private:
    RansVariant variant_ = RansVariant::Byte;
    int symbol_bits_ = 0;
    int bypass_bits_ = 0;
    uint32_t bypass_max_ = 0;
    std::vector<RansDist> dists_;
    std::vector<RansEncSym> enc_syms_;
    std::vector<uint32_t> cdf_table_;
};

// Streaming encoder. Data is encoded back-to-front; flush() exposes the
// [ptr, end) byte range, valid until reset() or destruction.
class RansEncoder {
public:
    explicit RansEncoder(RansVariant variant, size_t initial_capacity = 65536);
    rkvc::Status encode(const RansCoder& coder,
                        std::span<const int32_t> indices,
                        std::span<const int32_t> values);
    rkvc::Status flush(const uint8_t** out, size_t* out_size);
    void reset() noexcept;

private:
    bool grow();
    void write_byte(uint8_t v);
    void write_unit32(uint32_t v);
    void renorm_byte(uint32_t x_max);
    void renorm_64(uint64_t x_max);
    void put_sym_byte(const RansEncSym& s);
    void put_sym_64(const RansEncSym& s);
    void put_raw(uint32_t start, uint32_t freq, uint32_t scale_bits);
    void bypass(const RansCoder& c, uint32_t v);

    RansVariant variant_;
    uint64_t state_ = 0;
    std::vector<uint8_t> buf_;
    size_t ptr_ = 0;  // write position, grows downward
    bool flushed_ = false;
    bool oom_ = false;
};

class RansDecoder {
public:
    explicit RansDecoder(RansVariant variant);
    rkvc::Status open(std::span<const uint8_t> data);
    rkvc::Status decode(const RansCoder& coder, std::span<int32_t> values,
                        std::span<const int32_t> indices);
    bool check_eof() const noexcept;

private:
    bool read_byte(uint8_t& out) noexcept;
    bool read_unit32(uint32_t& out) noexcept;
    bool init_state();
    uint32_t get(uint32_t scale_bits) const noexcept;
    bool advance(uint32_t start, uint32_t freq, uint32_t scale_bits) noexcept;
    bool bypass(const RansCoder& c, uint32_t& out) noexcept;

    RansVariant variant_;
    uint64_t state_ = 0;
    const uint8_t* data_ = nullptr;
    size_t size_ = 0;
    size_t pos_ = 0;
    bool opened_ = false;
};

rkvc::Result<std::vector<uint8_t>> rans_encode(const RansCoder& coder,
                                               std::span<const int32_t> indices,
                                               std::span<const int32_t> values,
                                               rkvc::Diag* diag = nullptr);
rkvc::Status rans_decode(const RansCoder& coder, std::span<int32_t> values,
                         std::span<const int32_t> indices,
                         std::span<const uint8_t> data);

}  // namespace mlvc
